#!/bin/bash
# Auto-manage Pull Requests

PROJECT_PATH="${1:-.}"
GH_TOKEN="${GITHUB_TOKEN:-}"

cd "$PROJECT_PATH"

log() {
    echo "[$(date '+%H:%M:%S')] $1"
}

check_gh_cli() {
    if ! command -v gh &> /dev/null; then
        log "⚠️  GitHub CLI (gh) not found. Installing..."
        
        # Try to install gh CLI
        if [ "$(uname)" = "Darwin" ]; then
            brew install gh 2>/dev/null || {
                log "❌ Failed to install gh via Homebrew"
                return 1
            }
        elif [ "$(uname)" = "Linux" ]; then
            curl -s https://packagecloud.io/install/repositories/github/cli/github-cli.script | sudo bash 2>/dev/null || {
                log "❌ Failed to install gh via packagecloud"
                return 1
            }
            apt-get install gh -y 2>/dev/null || true
        fi
        
        # Verify installation
        if ! command -v gh &> /dev/null; then
            log "❌ GitHub CLI still not found. Please install manually:"
            log "   macOS: brew install gh"
            log "   Linux: https://cli.github.com/"
            return 1
        fi
    fi
    
    # Check if authenticated
    if ! gh auth status &> /dev/null; then
        log "🔐 Not authenticated with GitHub. Running: gh auth login"
        gh auth login --with-token <<< "$GH_TOKEN" || {
            log "❌ Authentication failed"
            return 1
        }
    fi
    
    return 0
}

create_pr() {
    local BRANCH="${1:-}"
    local TITLE="${2:-AI Auto-Generated PR}"
    local BODY="${3:-Automated PR from OpenClaw AI Dev workflow}"
    
    if [ -z "$BRANCH" ]; then
        # Detect current branch
        BRANCH=$(git rev-parse --abbrev-ref HEAD)
        
        if [ "$BRANCH" = "HEAD" ] || [ "$BRANCH" = "master" ] || [ "$BRANCH" = "main" ]; then
            log "❌ Cannot create PR from main/master branch. Please checkout a feature branch first."
            return 1
        fi
    fi
    
    # Check if branch is already pushed
    if ! git ls-remote --exit-code origin "$BRANCH" &> /dev/null; then
        log "📤 Pushing branch: $BRANCH"
        git push -u origin "$BRANCH" 2>&1 || {
            log "❌ Failed to push branch"
            return 1
        }
    fi
    
    # Check if PR already exists
    EXISTING_PR=$(gh pr list --head "$BRANCH" --state open --json number,url --jq '.[0].number' 2>/dev/null || echo "")
    
    if [ -n "$EXISTING_PR" ]; then
        log "ℹ️  PR #${EXISTING_PR} already exists for branch $BRANCH"
        
        # Update PR description if needed
        CURRENT_DESC=$(gh pr view "$EXISTING_PR" --json body --jq '.body' 2>/dev/null || echo "")
        
        if [ "$CURRENT_DESC" != "$BODY" ]; then
            log "📝 Updating PR description..."
            gh pr edit "$EXISTING_PR" --body "$BODY" 2>&1 || true
        fi
        
        return 0
    fi
    
    # Create new PR
    log "🔀 Creating Pull Request..."
    
    BASE_BRANCH=$(git branch --show-current)
    if [ -z "$BASE_BRANCH" ]; then
        BASE_BRANCH="main"
    fi
    
    # Generate PR title and body
    if [ "$TITLE" = "AI Auto-Generated PR" ]; then
        # Get latest commit message
        TITLE=$(git log -1 --pretty=format:"%s" | head -c 50)
        TITLE="${TITLE}..."
    fi
    
    BODY="${BODY}

---
*This PR was automatically generated by OpenClaw AI Dev*"
    
    # Create PR with gh CLI
    PR_OUTPUT=$(gh pr create \
        --title "$TITLE" \
        --body "$BODY" \
        --head "$BRANCH" \
        --base "$BASE_BRANCH" \
        2>&1)
    
    if [ $? -eq 0 ]; then
        log "✅ PR created successfully!"
        
        # Extract PR number and URL from output
        echo "$PR_OUTPUT" | grep -E "#[0-9]+|https://" || true
        
        return 0
    else
        log "❌ Failed to create PR:"
        echo "$PR_OUTPUT" | head -10
        return 1
    fi
}

list_prs() {
    log "📋 Open Pull Requests:"
    
    gh pr list --state open --json number,title,headRefName,url --jq '.[] | "#\(.number) \(.title) (\(.headRefName))" - "\(.url)"' 2>/dev/null || {
        log "⚠️  Could not fetch PRs. Is gh CLI configured?"
        return 1
    }
}

merge_pr() {
    local PR_NUMBER="${1:-}"
    
    if [ -z "$PR_NUMBER" ]; then
        # Get latest open PR
        PR_NUMBER=$(gh pr list --state open --json number --jq '.[0].number' 2>/dev/null || echo "")
        
        if [ -z "$PR_NUMBER" ]; then
            log "❌ No open PR found to merge"
            return 1
        fi
        
        log "Merging latest PR: #$PR_NUMBER"
    fi
    
    # Check CI status
    CI_STATUS=$(gh pr checks "$PR_NUMBER" --json name,state --jq '.[] | select(.state!="SUCCESS") | .name' 2>/dev/null || echo "")
    
    if [ -n "$CI_STATUS" ]; then
        log "⚠️  Some checks are not passing:"
        echo "$CI_STATUS" | sed 's/^/   /'
        
        read -p "Continue merge anyway? (y/N) " -n 1 -r
        echo
        
        if [[ ! $REPLY =~ ^[Yy]$ ]]; then
            log "❌ Merge cancelled"
            return 1
        fi
    fi
    
    # Auto-merge PR
    log "🔀 Merging PR #$PR_NUMBER..."
    
    MERGE_OUTPUT=$(gh pr merge "$PR_NUMBER" \
        --merge \
        --delete-branch \
        2>&1)
    
    if [ $? -eq 0 ]; then
        log "✅ PR #$PR_NUMBER merged successfully!"
        
        echo "$MERGE_OUTPUT" | grep -E "Merged|Deleted" || true
        
        return 0
    else
        log "❌ Failed to merge PR:"
        echo "$MERGE_OUTPUT" | head -10
        return 1
    fi
}

# Main execution
case "${2:-create}" in
    create)
        check_gh_cli || exit 1
        create_pr "${3:-}" "${4:-}" "${5:-}"
        ;;
    list)
        check_gh_cli || exit 1
        list_prs
        ;;
    merge)
        check_gh_cli || exit 1
        merge_pr "$3"
        ;;
    status)
        check_gh_cli || exit 1
        log "📊 PR Status:"
        
        OPEN_PRS=$(gh pr list --state open --json number,title,headRefName,url --jq 'length' 2>/dev/null || echo "0")
        CLOSED_PRS=$(gh pr list --state closed --json number,title,headRefName,url --jq 'length' 2>/dev/null || echo "0")
        
        log "   Open PRs: $OPEN_PRS"
        log "   Closed PRs: $CLOSED_PRS"
        ;;
    *)
        echo "Usage: auto-pr.sh [project_path] [command] [args]"
        echo ""
        echo "Commands:"
        echo "  create  - Create new PR (default)"
        echo "  list    - List open PRs"
        echo "  merge   - Merge latest or specified PR"
        echo "  status  - Show PR statistics"
        ;;
esac
